features:

  # 为 Chemdah 启用 FancyNPC 支持
  fancynpc-support: false

  # 启用 ChoTenChem 提供的计分板
  scoreboard: false

# ChoTenChem 提供的追踪计分板
# 使用时请禁用原版任务追踪的计分板选项，你可以使用VSCode批量替换启用计分板的选项
scoreboard:

  # 计分板更新周期，重启生效
  update: 40

  title: "ChoTenChem 任务追踪"

  lines:
    - type: text
      content: |
        &7====
        &6任务计分板
        &7

    - type: task

      # maximum: 4 - 限制最多插入4条任务

      # 过滤器，不填默认all
      # all - 不予过滤，例如：
      # 任务1 - 已完成
      # 任务2 - 已完成
      # 任务3 - 未完成
      # smart - 智能任务解析，优先展示未完成的任务，例如：
      # 任务3 - 未完成
      # 任务1 - 已完成
      # 任务2 - 已完成
      # progress - 只展示进行中的任务，例如：
      # 任务3 - 未完成
      filter: all

      completed: "&8&m&o#{id} {meta:name}&r &a已完成"
      in-progress: "&8#{id} &7{meta:name} &e{progress:1}/{target:1} &7({percent:1}%)"
      no-progress: "&8#{id} &7{meta:name} &c未开始"

    - type: text
      content: |
        &7====

placeholders:

  # 任务解析
  # %chotenchem_task_任务名称_子任务%
  # 任务名使用TRACKING代表使用追踪中的任务
  # 例如 %chotenchem_task_ILoveChoTenChan_1% - 获取第1个子任务（从1起数）
  # 例如 %chotenchem_task_ILoveChoTenChan_*taskaaa% - 获取子任务"taskaaa"
  task:
    filter: all
    completed: "&8&m&o#{id} {meta:name}&r &a已完成"
    in-progress: "&8#{id} &7{meta:name} &e{progress:1}/{target:1} &7({percent:1}%)"
    no-progress: "&8#{id} &7{meta:name} &c未开始"

  # 智能任务解析
  # %chotenchem_smart-task_任务名称_当前项%，当前项必须为数字类型
  # 任务名使用TRACKING代表使用追踪中的任务
  # 例如 %chotenchem_smart-task_ILoveChoTenChan_1%
  #
  # 该选项在展示非 Chemdah 提供的计分板时非常有用。
  # 尤其是您希望将任务限制在部分计分板内的时候。
  # 示例如下:
  # 任务ILoveChoTenChan中，子任务1和3已完成，2正在进行，4还没有进展，那么展示的就是：
  # %chotenchem_smart-task_ILoveChoTenChan_3% -> &7子任务2名称 &e1/5 &7(20%)
  # %chotenchem_smart-task_ILoveChoTenChan_4% -> &7子任务4名称 &c未开始
  # %chotenchem_smart-task_ILoveChoTenChan_1% -> &7子任务1名称&r &a已完成
  # %chotenchem_smart-task_ILoveChoTenChan_2% -> &7子任务3名称&r &a已完成
  smart-task:
    filter: smart
    completed: "&8&m&o#{id} {meta:name}&r &a已完成"
    in-progress: "&8#{id} &7{meta:name} &e{progress:1}/{target:1} &7({percent:1}%)"
    no-progress: "&8#{id} &7{meta:name} &c未开始"

  # 未完成的任务解析
  # %chotenchem_task_任务名称_当前项%，当前项必须为数字类型
  # 任务名使用TRACKING代表使用追踪中的任务
  # 示例如下:
  # 任务ILoveChoTenChan中，子任务1和3已完成，2正在进行，4还没有进展，那么展示的就是：
  # %chotenchem_uncompleted-task_ILoveChoTenChan_1% -> &7子任务2名称 &e1/5 &7(20%)
  # %chotenchem_uncompleted-task_ILoveChoTenChan_2% -> &7子任务4名称 &c未开始
  # %chotenchem_uncompleted-task_ILoveChoTenChan_3% -> (空字符串)
  # %chotenchem_uncompleted-task_ILoveChoTenChan_4% -> (空字符串)
  uncompleted-task:
    filter: progress
    completed: " "
    in-progress: "&8#{id} &7{meta:name} &e{progress:1}/{target:1} &7({percent:1}%)"
    no-progress: "&8#{id} &7{meta:name} &c未开始"


  # 自定义的任务解析
  # 允许自定义任务的其他格式
  # %chotenchem_<自定义名>_任务名称_子任务%
  # 任务名使用TRACKING代表使用追踪中的任务
  # 例如 %chotenchem_custom-task_ILoveChoTenChan_taskaaa%
  custom-task:
    filter: all
    completed: "&8&m&o#{id} {meta:name}&r &a已完成"
    in-progress: "&8#{id} &7{meta:name} &e{progress:1}/{target:1} &7({percent:1}%)"
    no-progress: "&8#{id} &7{meta:name} &c未开始"